import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/*
 * searching.java
 *
 * Created on Dec 7, 2019, 1:35:10 AM
 */

/**
 *
 * @author Umesh Singh
 */
public class searching extends javax.swing.JFrame {

    /** Creates new form searching */
    public searching() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Andalus", 1, 18));
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Californian FB", 0, 18));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bathinda", "Amritsar", "Ludhiana", "Chandigarh", "Jalandhar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Californian FB", 0, 18));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jaipur", "bathinda", "Amritsar", "Delhi", "Ludhiana", "Mumbai", "Chandigarh", "Jalandhar" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24));
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24));
        jLabel3.setText("To");

        jButton3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton3.setText("calculate amount");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24));
        jLabel4.setText("ID");

        jTable1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus no", "From", "Destination"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton4.setText("BOOK TICKETS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 48)); // NOI18N
        jLabel13.setText("P.R.T.C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addGap(3, 3, 3)))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel13)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
MainMenu a= new MainMenu();
a.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/roadways","root","mgn");
        Statement stmt = (Statement) con.createStatement();
        String query =" Select * from buses where fromm ='"+jComboBox1.getSelectedItem()+"' and destination ='"+jComboBox2.getSelectedItem()+"'";
        ResultSet rs =stmt.executeQuery(query);
  
       while(rs.next()) {String a =rs.getString("busno");String d = rs.getString("fromm");
        String dN = rs.getString("destination");
     
        model.addRow(new Object[] {a,d,dN});
        }
 
    }catch(Exception e) {
        JOptionPane.showMessageDialog(null,e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   double r=0;String f=(String) jComboBox1.getSelectedItem();String y=(String) jComboBox2.getSelectedItem();
   
       




   String ID = jTextField1.getText();
        String str = null;
        Statement stmt=null;
        ResultSet rs = null;
        try
        {

            Class.forName("java.sql.Driver");

            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/menegerie", "root", "mgn");
            stmt = (Statement) conn.createStatement();
            String sql = "select age,id from roadways where id = '" + ID + "'";
            rs = stmt.executeQuery(sql);
           if (rs.next())
           {
               String q=rs.getString("id");

            int s=rs.getInt("age");

            if(q.equals(ID))
{

    if(s<=12||s>=60){
        if(f.equals("bathinda")&&y.equals("Jaipur")){r=400;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
         if(f.equals("bathinda")&&y.equals("Amritsar")){r=300;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
         if(f.equals("bathinda")&&y.equals("Delhi")){r=932;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
         if(f.equals("bathinda")&&y.equals("Ludhiana")){r=140;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
         if(f.equals("bathinda")&&y.equals("Chandigarh")){r=120;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
         if(f.equals("bathinda")&&y.equals("Jalandhar")){r=110;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
         if(f.equals("bathinda")&&y.equals("Mumbai")){r=4765;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
         if(f.equals("Amritsar")&&y.equals("Jaipur")){r=500;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Amritsar")&&y.equals("bathinda")){r=290;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Amritsar")&&y.equals("Jalandhar")){r=48;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Amritsar")&&y.equals("Ludhiana")){r=90;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Amritsar")&&y.equals("Chandigarh")){r=210;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Amritsar")&&y.equals("Delhi")){r=680;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Amritsar")&&y.equals("Mumbai")){r=4200;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Jalandhar")&&y.equals("Jaipur")){r=367;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
        if(f.equals("Jalandhar")&&y.equals("Amritsar")){r=48;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}
if(f.equals("Jalandhar")&&y.equals("Chandigarh")){r=167;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r/2+" with 50% discount");}

        if(f.equals("Jalandhar")&&y.equals("Ludhiana")){r=36;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}

        if(f.equals("Jalandhar")&&y.equals("Delhi")){r=267;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}

        if(f.equals("Jalandhar")&&y.equals("Mumbai")){r=4067;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}

        if(f.equals("Jalandhar")&&y.equals("bathinda")){r=64;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
if(f.equals("Chandigarh")&&y.equals("Jaipur")){r=671;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
        if(f.equals("Chandigarh")&&y.equals("bathinda")){r=87;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
        if(f.equals("Chandigarh")&&y.equals("Ludhiana")){r=360;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
        if(f.equals("Chandigarh")&&y.equals("Amritsar")){r=98;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
        if(f.equals("Chandigarh")&&y.equals("Delhi")){r=95;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
        if(f.equals("Chandigarh")&&y.equals("Mumbai")){r=3067;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
        if(f.equals("Chandigarh")&&y.equals("Jalandhar")){r=60;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
if(f.equals("Ludhiana")&&y.equals("Jaipur")){r=370;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
        if(f.equals("Ludhiana")&&y.equals("Jalandhar")){r=36;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
 if(f.equals("Ludhiana")&&y.equals("Amritsar")){r=52;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}

         if(f.equals("Ludhiana")&&y.equals("Chandigarh")){r=354;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
 if(f.equals("Ludhiana")&&y.equals("Mumbai")){r=4367;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
 if(f.equals("Ludhiana")&&y.equals("bathinda")){r=87;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}
  if(f.equals("Ludhiana")&&y.equals("Delhi")){r=387;JOptionPane.showMessageDialog(null,"ur amount is "+r/2+" with 50% discount");}

    }
     if(f.equals("bathinda")&&y.equals("Jaipur")){r=400;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
         if(f.equals("bathinda")&&y.equals("Amritsar")){r=300;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
         if(f.equals("bathinda")&&y.equals("Delhi")){r=932;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
         if(f.equals("bathinda")&&y.equals("Ludhiana")){r=140;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
         if(f.equals("bathinda")&&y.equals("Chandigarh")){r=120;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
         if(f.equals("bathinda")&&y.equals("Jalandhar")){r=110;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
         if(f.equals("bathinda")&&y.equals("Mumbai")){r=4765;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
         if(f.equals("Amritsar")&&y.equals("Jaipur")){r=500;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
        if(f.equals("Amritsar")&&y.equals("bathinda")){r=290;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
        if(f.equals("Amritsar")&&y.equals("Jalandhar")){r=48;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
        if(f.equals("Amritsar")&&y.equals("Ludhiana")){r=90;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
        if(f.equals("Amritsar")&&y.equals("Chandigarh")){r=210;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
        if(f.equals("Amritsar")&&y.equals("Delhi")){r=680;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
        if(f.equals("Amritsar")&&y.equals("Mumbai")){r=4200;JOptionPane.showMessageDialog(null,"ur amount is Rs."+r);}
        if(f.equals("Jalandhar")&&y.equals("Jaipur")){r=367;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Jalandhar")&&y.equals("Amritsar")){r=48;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
if(f.equals("Jalandhar")&&y.equals("Chandigarh")){r=167;JOptionPane.showMessageDialog(null,"ur amount is "+r);}

        if(f.equals("Jalandhar")&&y.equals("Ludhiana")){r=36;JOptionPane.showMessageDialog(null,"ur amount is "+r);}

        if(f.equals("Jalandhar")&&y.equals("Delhi")){r=267;JOptionPane.showMessageDialog(null,"ur amount is "+r);}

        if(f.equals("Jalandhar")&&y.equals("Mumbai")){r=4067;JOptionPane.showMessageDialog(null,"ur amount is "+r);}

        if(f.equals("Jalandhar")&&y.equals("bathinda")){r=64;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
if(f.equals("Chandigarh")&&y.equals("Jaipur")){r=671;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Chandigarh")&&y.equals("bathinda")){r=87;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Chandigarh")&&y.equals("Ludhiana")){r=360;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Chandigarh")&&y.equals("Amritsar")){r=98;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Chandigarh")&&y.equals("Delhi")){r=95;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Chandigarh")&&y.equals("Mumbai")){r=3067;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Chandigarh")&&y.equals("Jalandhar")){r=60;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
if(f.equals("Ludhiana")&&y.equals("Jaipur")){r=370;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
        if(f.equals("Ludhiana")&&y.equals("Jalandhar")){r=36;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
 if(f.equals("Ludhiana")&&y.equals("Amritsar")){r=52;JOptionPane.showMessageDialog(null,"ur amount is "+r);}

         if(f.equals("Ludhiana")&&y.equals("Chandigarh")){r=354;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
 if(f.equals("Ludhiana")&&y.equals("Mumbai")){r=4367;JOptionPane.showMessageDialog(null,"ur amount is "+r);}
 if(f.equals("Ludhiana")&&y.equals("bathinda")){r=87;JOptionPane.showMessageDialog(null,"ur amount is "+r);}

 if(f.equals("Ludhiana")&&y.equals("Delhi")){r=387;JOptionPane.showMessageDialog(null,"ur amount is "+r);}

}
}
else
{JOptionPane.showMessageDialog(null,"INVALID ID");

}
} catch (Exception e) {JOptionPane.showMessageDialog(null,e.getMessage());}

         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
ticketbooking a= new ticketbooking();
a.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
