import java.sql.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/*
 * ticketbooking.java
 *
 * Created on Jan 10, 2020, 8:59:30 PM
 */

/**
 *
 * @author Umesh Singh
 */
public class ticketbooking extends javax.swing.JFrame {

    /** Creates new form ticketbooking */
    public ticketbooking() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jButton4.setText("PAYMENT");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel1.setText("TICKET BOOKING");

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setText("Total no. of pessenger");

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setText("age less then 12");

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setText("age b/w 12-65");

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18));
        jLabel5.setText("age greater then 65");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14));
        jButton1.setText("CALUCULATE AMOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bathinda", "Amritsar", "Ludhiana", "Chandigarh", "Jalandhar" }));

        jComboBox2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jaipur", "bathinda", "Amritsar", "Delhi", "Ludhiana", "Mumbai", "Chandigarh", "Jalandhar" }));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18));
        jLabel6.setText("FROM");

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18));
        jLabel7.setText("DESTINATION");

        jButton2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14));
        jButton2.setText("Book Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel8.setText("ID");

        jButton5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14));
        jButton5.setText("PAYMENT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 48));
        jLabel13.setText("P.R.T.C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(id)
                                .addGap(271, 271, 271))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(17, 17, 17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33))
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 double r=0;
 String f=(String) jComboBox1.getSelectedItem();
 String y=(String) jComboBox2.getSelectedItem();
 int a = Integer.parseInt(jTextField2.getText());
 int b = Integer.parseInt(jTextField3.getText());
 int c = Integer.parseInt(jTextField4.getText());


  if(f.equals("bathinda")&&y.equals("Jaipur")){r=400;}
  if(f.equals("bathinda")&&y.equals("Amritsar")){r=300;}
  if(f.equals("bathinda")&&y.equals("Delhi")){r=932;}
  if(f.equals("bathinda")&&y.equals("Ludhiana")){r=140;}
  if(f.equals("bathinda")&&y.equals("Chandigarh")){r=120;}
  if(f.equals("bathinda")&&y.equals("Mumbai")){r=2000;}
  if(f.equals("bathinda")&&y.equals("Jalandhar")){r=64;}
  if(f.equals("Amritsar")&&y.equals("Jaipur")){r=370;}
  if(f.equals("Amritsar")&&y.equals("bathinda")){r=300;}
  if(f.equals("Amritsar")&&y.equals("Delhi")){r=900;}
  if(f.equals("Amritsar")&&y.equals("Ludhiana")){r=100;}
  if(f.equals("Amritsar")&&y.equals("Mumbai")){r=2050;}
  if(f.equals("Amritsar")&&y.equals("Chandigarh")){r=150;}
  if(f.equals("Amritsar")&&y.equals("Jalandhar")){r=70;}
  if(f.equals("Jalandhar")&&y.equals("Ludhiana")){r=36;}
  if(f.equals("Jalandhar")&&y.equals("Jaipur")){r=436;}
  if(f.equals("Jalandhar")&&y.equals("Amritsar")){r=70;}
  if(f.equals("Jalandhar")&&y.equals("Chandigarh")){r=250;}
  if(f.equals("Jalandhar")&&y.equals("Delhi")){r=267;}
  if(f.equals("Jalandhar")&&y.equals("Mumbai")){r=4067;}
  if(f.equals("Jalandhar")&&y.equals("bathinda")){r=64;}
  if(f.equals("Chandigarh")&&y.equals("Jaipur")){r=671;}
  if(f.equals("Chandigarh")&&y.equals("bathinda")){r=67;}
  if(f.equals("Chandigarh")&&y.equals("Amritsar")){r=100;}
  if(f.equals("Chandigarh")&&y.equals("Delhi")){r=451;}
  if(f.equals("Chandigarh")&&y.equals("Ludhiana")){r=354;}
  if(f.equals("Chandigarh")&&y.equals("Mumbai")){r=1971;}
  if(f.equals("Chandigarh")&&y.equals("Jalandhar")){r=250;}
  if(f.equals("Ludhiana")&&y.equals("Jaipur")){r=487;}
  if(f.equals("Ludhiana")&&y.equals("Jalandhar")){r=36;}
  if(f.equals("Ludhiana")&&y.equals("Amritsar")){r=52;}
  if(f.equals("Ludhiana")&&y.equals("Chandigarh")){r=354;}
  if(f.equals("Ludhiana")&&y.equals("Mumbai")){r=4367;}
  if(f.equals("Ludhiana")&&y.equals("bathinda")){r=87;}
  if(f.equals("Ludhiana")&&y.equals("Delhi")){r=387;}
  if(f.equals(y)){r=0;}
  float v = ((float)(r / 3.0)) * a;
  float w = ((float)(r / 2.0))*c;
  float x = ((float)r)*b;
  float z = v+w+x;
  JOptionPane.showMessageDialog(null,"your amount is Rs."+z);
    }




         // TODO add your handling code here:
    

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   try
   {
            Class.forName("java.sql.DriverManager");
            String database = "jdbc:mysql://localhost:3306/roadways";
            Connection conn = DriverManager.getConnection(database, "root", "mgn");
            Statement stmt = conn.createStatement();
            String sql ="select id from roadways where id ='"+id.getText()+"'";
            ResultSet rs =stmt.executeQuery(sql);
               while(rs.next()){
               String q=rs.getString("id");
               if(q.equals(id.getText())){
               String sq = "insert into ticketbooking values (" + jTextField1.getText()+","+  jTextField2.getText() +"," + jTextField3.getText() + "," + jTextField4.getText()+",'"+id.getText()+"')";
              stmt.executeUpdate(sq);
        JOptionPane.showMessageDialog(null,"YOUR TICKETS ARE BOOKED FOR PAYMENT CLICK ON PAMENT BUTTON ");}
  else{JOptionPane.showMessageDialog(null,"YOUR ID DOES NOT EXIST OR FILL ALL REQUIREMENTS " );}
}
            } catch( Exception e) {
                JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY OR FILL ALL REQUIREMENTS" );
            }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          System.exit(0); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
payment a = new payment();
a.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
